# config/routes.yaml
index:
    path: /
    controller: App\Controller\DefaultController::index
#articles_list:
#    path: /articles
#    # the controller value has the format 'controller_class::method_name'
#    controller: App\Controller\ArticlesController::list
#    methods:    GET
