security:
  encoders:
    App\Entity\User: bcrypt
  providers:
    database_users:
      entity:
        class: App\Entity\User,
        property: email
  firewalls:
    main:
      form_login:
        check_path: login
        login_path: login
        default_target_path: homepage
      logout:
        path: logout